name: Deploy to Databricks Apps

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks --version

      - name: Configure Databricks CLI
        run: |
          mkdir -p ~/.databricks
          echo "[DEFAULT]" > ~/.databricks/config
          echo "host = $DATABRICKS_HOST" >> ~/.databricks/config
          echo "token = $DATABRICKS_TOKEN" >> ~/.databricks/config
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

      - name: Update Deployment (Dev)
        if: github.ref == 'refs/heads/dev'
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          ENV: DEV
          RESOURCE_KEY: ${{ secrets.RESOURCE_KEY }}
        run: |
          databricks sync . /Workspace/Users/ajaypalsallh@gmail.com/testing-app-deploy-dev
          databricks apps deploy test-deploy-dev --source-code-path /Workspace/Users/ajaypalsallh@gmail.com/testing-app-deploy-dev --resource-key $RESOURCE_KEY --env $ENV

      - name: Update Deployment (Main)
        if: github.ref == 'refs/heads/main'
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          ENV: PROD
          RESOURCE_KEY: ${{ secrets.RESOURCE_KEY }}
        run: |
          databricks sync . /Workspace/Users/ajaypalsallh@gmail.com/testing-app-deploy
          databricks apps deploy test-app --source-code-path /Workspace/Users/ajaypalsallh@gmail.com/testing-app-deploy --resource-key $RESOURCE_KEY --env $ENV